#version: '2'

#services:
#  frontend:
#    image: nginx:1.15
#    container_name: nginx
#    volumes:
#      - ./docker/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 80:80
#      - 443:443
#    networks:
#      - front
#    restart: always
#  helpy:
#    build: .
#    restart: always
#    networks:
#      - front
#      - back
#    volumes:
#      - rails-assets:/helpy/public
#    env_file: docker/.env.sample
#    depends_on:
#      - postgres
#    ports: 
#      - "3000:3000"
#  postgres:
#    image: postgres:9.4
#    restart: always
#    networks:
#      - back
#    env_file: docker/.env.sample
#    volumes:
#      - ./postgres:/var/lib/postgresql/data

#volumes:
#  rails-assets:
#    driver: local

#networks:
#  front:
#    driver: bridge
#  back:
#    driver: bridge
version: '2'

services:
  frontend:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - front
    restart: always

  helpy:
    build: .
    restart: always
    networks:
      - front
    volumes:
      - rails-assets:/helpy/public
    env_file: docker/.env.sample
    ports: 
      - "3000:3000"
    environment:
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=helpy_production
      - POSTGRES_USER=helpy
      - POSTGRES_PASSWORD=some_secure_pg_password_change_in_production

volumes:
  rails-assets:
    driver: local

networks:
  front:
    driver: bridge


